import { Inter } from "next/font/google";
import "./globals.css";
import "./prime-react.css";
import RecoilContextProvider from "@/recoilstore/store";
import GlobalToast from "@/component/Global_Toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NutsBee",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          href="/favicon.ico"
          style={{ mixBlendMode: "multiply" }}
        />
      </head>
      <body className={inter.className}>
        <RecoilContextProvider>
          <GlobalToast />
          {children}
        </RecoilContextProvider>
      </body>
    </html>
  );
}
