import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./prime-react.css";
import Header from "../component/Header";
import GoToTop from "@/component/GoToTop";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "NutsBee",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <link rel='icon' href='/favicon.ico' /> 
      </head>
      <body className={inter.className}>
        <div className="min-h-100vh h-full w-full flex flex-col text-orange-500 md:px-10 ">
          <Header />
          <GoToTop />

          <main
            // className="mt-2 transition-transform duration-300 p-0 flex-1 overflow-hidden bg-gray-300"
            className="flex-1 p-1"
          >
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
